import = ["~/.config/alacritty/alacritty-theme/themes/aura.toml"]

[window]
decorations = "Full"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 17.5
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"
